title: Site
columns:
  - width: 1/2
    sections:
      decades:
        headline: Décennies
        type: pages
        create: decade
        templates:
          - decade


  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        templates:
          - home
          - default